### ISSUE TITLE
size mismatch for up_blocks.3.motion_modules.0.temporal_transformer.transformer_blocks.0.attention_blocks.1.pos_encoder.pe: copying a param with shape torch.Size([1, 24, 320]) from checkpoint, the shape in current model is torch.Size([1, 32, 320]).

### ISSUE THREAD

**Issue by lihuining** [xizaoqu/MOFT#1]
When I run the process.ipynb,in the line do_inversion I encountered this error,can you give me any advice about how to solve this?

**Comment by xizaoqu** [comment]
Hi, can you provide where you download the checkpoint of Animatediff?

**Comment by lihuining** [comment]
> Hi, can you provide where you download the checkpoint of Animatediff?

I downloaded all the models from this link,https://huggingface.co/guoyww/animatediff/tree/main.

**Comment by xizaoqu** [comment]
I tested it and did not find such an error. Does your folder look like this?
![image](https://github.com/user-attachments/assets/f0203cec-109f-42b0-ae88-1b2ce9257193)

**Comment by lihuining** [comment]
> I tested it and did not find such an error. Does your folder look like this? ![image](https://private-user-images.githubusercontent.com/45515569/395937898-f0203cec-109f-42b0-ae88-1b2ce9257193.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMzYyMzUsIm5iZiI6MTczNDMzNTkzNSwicGF0aCI6Ii80NTUxNTU2OS8zOTU5Mzc4OTgtZjAyMDNjZWMtMTA5Zi00MmIwLWFlODgtMWIyY2U5MjU3MTkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDA3NTg1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1ZGM5ZWMwMDU4OWY3NDcyZGVhZDdhOWFkMDRhMmE2N2Q1ZmQzODk3NzU3NjM4MzFkNWQ0YzkwMGI4YWE5NGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.izyREV_oA3bteaQ4HhsC0_X4cqlcGO8zHCD5h5UdxD8)

Oh, I realized that I mistakenly linked v1 to v2. Thank you very much for your response.
